language: node_js

node_js:
  - '7.7'

services:
  - docker

env:
  global:
    - NODE_ENV: "test"
    - DB_USER: "postgres"
    - CXX: g++-4.8
    # DOCKER_USERNAME
    - secure: IXZ8Jskg91eCRgY2a3VmIAo1kCpmeiwnuPOdBYFXzlDRL/gp0k7p4LeyCsP+ztVhNg8Yg3RhcRNhg4Jzfl/TKXQHlel4EL+SXZrgux1i1+zvzsl2syPj53PswlFh3WCzovUjfPnYzU1bIS6R1xDGzUKcWNdAXJ735aVvqYh0RCQ=
    # DOCKER_PASSWORD
    - secure: JMF9r9a6GgIWgnjI6IgfdqcTfii4MO6/DHhH1bIqruIoVwNe+y4ioIS7/OPw6jQ43uvaFMpbourTBgcOyju0/e5B5gpktPb+Wq0LHcI58C5N7a0IsdltvrNjC7aIliuMcbPsdnVUeD3jbcz80vqPaJcOs23P6gUro0ArbwsMAn0=

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - psql -c 'create database opendatacensus_test;' -U postgres

script:
  - echo 'Tests are skipped'

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make ci-push-tag TAG="${TRAVIS_PULL_REQUEST_BRANCH////_}"; fi'

deploy:
  # deploy master to latest tag
  - provider: script
    script: make ci-push
    on:
      branch: master
