site_name: Open Data Census
site_description: Documentation for the Open Data Census application
site_url: http://census.okfn.org/
repo_url: https://github.com/okfn/opendatacensus
pages:
  - Home: 'index.md'
  - Global Census: 'global/index.md'
  - Local Census: 'local/index.md'
  - Site Admins: 'site-admins/index.md'
  - Sys Admins: 'sys-admins/index.md'
  - Survey Flow: 'survey-flow/index.md'
  - Event Guide: 'eventguide/index.md'
  - Contact: 'contact/index.md'
theme: readthedocs
markdown_extensions:
  - markdown_include.include:
      base_path: docs
google_analytics: ['UA-33874954-7', 'census.okfn.org']

